### ISSUE TITLE
No tab complete in the middle of a string 

### ISSUE THREAD

**Issue by MaxLeiter** [thelounge/thelounge#2684] opened 2018-07-29 22:12 UTC
* *Node version:* v10.7.0
* *Browser version:* 68.0.3440.75
* *Device, operating system:* macOS 10.13.4
* *The Lounge version:* 927da28

---

Write a sentence, move the cursor in the middle of the sentence,  try to tab-complete a nickname. No tab complete

**Comment by dgw** [comment] 2018-07-29 23:00
Duplicate of #1801

**Closed** 2018-07-29 23:11 UTC
