### ISSUE TITLE
Themes: Highlight input fields when tabbing/clicking through them

### ISSUE THREAD

**Issue by Zarthus** [thelounge/thelounge#3018] opened 2019-02-01 20:57 UTC
### Feature Description

I would like to see what input box I've currently got selected (at least in settings) so that I can more easily navigate through them with TAB.

Default browser behaviour [[sample jsfiddle](https://jsfiddle.net/8pecxmg5/)]:
![img](https://liefland.net/~zarthus/image/2019-02-01_f409a100844bf17340dd.png)

TheLounge behaviour (Default, Morning themes):
![img](https://liefland.net/~zarthus/image/2019-02-01_be0184d2bf.png)

**Comment by xPaw** [comment] 2019-02-01 21:02
Duplicate of #1872 #1873

**Closed by xPaw** 2019-02-01 21:02 UTC
