### ISSUE TITLE
Per-channel status messages settings

### ISSUE THREAD

**Issue by polux** [thelounge/thelounge#4033] opened 2020-08-14 14:41 UTC
### Feature Description

It would be nice to have per-channel status messages settings. On channels with a small set of users, I like to be notified when one of my friends joins or leaves. But activating status messages makes large channels with hundreds of users unreadable.

**Comment by xPaw** [comment] 2020-08-14 15:06
Duplicate of #85

**Closed by xPaw** 2020-08-14 15:06 UTC
Labels: Type: Feature
