### ISSUE TITLE
Add favorite/pinned messages per channel/server/global

### ISSUE THREAD

**Issue by woswos** [thelounge/thelounge#4080] opened 2020-09-15 11:17 UTC
### Feature Description
Hi!

You know, sometimes people tell important stuff on IRC, and you want to 'save' these messages. For these cases, I copy and paste messages to a text file on my computer. Instead, it would be great if we could pin or add certain messages to our 'favorites list' within the application.

That list can live under the settings menu, or we can have a new menu tab for these 'favorite' messages. I'm talking about something like this:

<img width="193" alt="Screen Shot 2020-09-15 at 2 54 24 PM" src="https://user-images.githubusercontent.com/10498874/93203499-96ae8a00-f765-11ea-9b92-a0852a1be2cb.png">

I'm happy to help with designing a wireframe for the 'favorites tab' and for other related components if the community is interested in the idea.

**Comment by xPaw** [comment] 2020-09-15 12:41
This could just as easily tie into the mentions window, where saving a message would put it there. I certainly don't see a reason to add separate UI/window for it.

**Comment by xPaw** [comment] 2020-09-29 10:35
Closing as a duplicate of #180, feel free to add comments there.

**Closed by xPaw** 2020-09-29 10:35 UTC
Labels: Type: Feature
