### ISSUE TITLE
Replace jquery-ui with a different (lightweight) drag and drop solution

### ISSUE THREAD

**Issue by xPaw** [thelounge/thelounge#932] opened 2017-02-18 19:10 UTC
We include jquery ui to implement channel sorting. There are couple of problems with it:
1. It's heavy
2. It does not work on mobile (no touch support)

**Comment by MaxLeiter** [comment] 2017-03-06 18:26
Some possible alternatives:

- [html5 drag and drop](https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API)
- [dragula](https://bevacqua.github.io/dragula/)
- [Stick to jquery ui but use Touch Punch for mobile support](http://touchpunch.furf.com/)

**Comment by YaManicKill** [comment] 2017-04-26 09:04
Do we need this in 2.3.0? I feel like, as the only PR we have has a lot of issues with it, it's probably best to leave it till 2.4

**Comment by astorije** [comment] 2017-04-26 12:00
I agree. Even though I highly appreciate the effort, the open PR is not in a mergeable state as it would essentially be a regression. With a bit of work and testing, it's definitely reachable shortly, but most likely not for 2.3.0.
Removing for now, as we are closing the features for 2.3.0.

**Comment by Raqbit** [comment] 2017-09-13 19:11
I was experimenting with the libraries @MaxLeiter noted, and except for the jquery option, they all allow 
dropping outside of the parent container. This is due to the limitations of the html5 drag & drop that they use. That said I don't think we need to limit this, as long as it doesn't do anything as a result (which is the default for most of these libraries).

**Comment by Raqbit** [comment] 2017-10-02 06:35
I'd like to take on this for hacktoberfest, since I've been experimenting with some solutions and already have something whipped up. Planning on opening a PR for discussion soon.

**Closed** 2019-02-16 18:01 UTC
Labels: Type: Feature
