### ISSUE TITLE
Umlaut e (Ë) not HTML escaped

### ISSUE THREAD

**Issue by megaxlr** [thelounge/thelounge#2485] opened 2018-05-30 08:42 UTC
Behaviour: 
![image](https://user-images.githubusercontent.com/8215278/40709216-d2003aa0-63f5-11e8-9ee5-2decda58aae1.png)

Expected Behaviour:
![image](https://user-images.githubusercontent.com/8215278/40709353-15c770a0-63f6-11e8-858f-dd78c954db75.png)

* *Node version:* 8.11.1
* *Browser version:* Opera (latest)
* *Device, operating system:* Debian GNU/Linux Testing
* *The Lounge version:* 2.7.1

---

Suggested fix: 
Extended checking for html-encoded characters (ref: http://www.starr.net/is/type/htmlcodes.html)

**Comment by xPaw** [comment] 2018-05-30 09:00
Duplicate of #1094

**Closed by xPaw** 2018-05-30 09:00 UTC
