### ISSUE TITLE
Support oembed for previews

### ISSUE THREAD

**Issue by fuzzy76** [thelounge/thelounge#2963] opened 2019-01-08 10:02 UTC
A lot of IRC clients does atleast video playback of YouTube videos inline. One general way to solve this would be https://oembed.com/

**Comment by xPaw** [comment] 2019-01-08 10:08
oembed directly doesn't solve this as you would still need to embed the youtube iframe (including all of its megabytes of scripts) for every video.

**Comment by fuzzy76** [comment] 2019-01-08 10:16
Ok, inline was probably not a good idea, but when expanded, like the current preview.

It could even be done inside the popup that shows up when clicking on images.

**Comment by xPaw** [comment] 2019-12-20 10:51
Gonna close this as duplicate of #14 to keep the discussion in one place.

**Closed by xPaw** 2019-12-20 10:51 UTC
Labels: Type: Feature
