### ISSUE TITLE
Emojis are too large in sent messages

### ISSUE THREAD

**Issue by makeworld-the-better-one** [thelounge/thelounge#4445] opened 2022-01-15 05:08 UTC
- _Node version:_ v14.18.1
- _Browser version:_ Firefox 95.0.2
- _Device, operating system:_ Laptop, Arch Linux
- _The Lounge version:_ v4.3.0

---

I am using Twemoji as the default emoji font on my computer. That is used by Firefox and therefore sites that use emoji without setting their own custom emoji font, like my TheLounge server.

I've noticed emojis are too large once messages are sent.

Sent message (too large):

![image](https://user-images.githubusercontent.com/25111343/149609754-fc8332b5-cc7b-4c33-b924-550780fe7572.png)

Message in text box before sending (good size):

![image](https://user-images.githubusercontent.com/25111343/149609766-312244b4-f3a2-4f0a-bd93-2a7ecf995656.png)

Thank you!

**Comment by dgw** [comment] 2022-01-15 05:24
Sounds like a good use case for custom CSS targeted at `span.emoji`.

**Comment by makeworld-the-better-one** [comment] 2022-01-16 01:01
When the Twemoji font is forced on websites by using Twemoji's JS lib, they recommend [this](https://github.com/twitter/twemoji#inline-styles) CSS:

```css
img.emoji {
   height: 1em;
   width: 1em;
   margin: 0 .05em 0 .1em;
   vertical-align: -0.1em;
}
```

> This will make sure emoji derive their width and height from the `font-size` of the text they're shown with. It also adds just a little bit of space before and after each emoji, and pulls them upwards a little bit for better optical alignment.

Obviously this won't work out of the box, but maybe something to base any new CSS off of.

**Comment by brunnre8** [comment] 2022-01-18 17:08
They aren't "too large", they are larger than normal by design.
That's a stylistic choice rather than a bug and easy to override either with themes or with custom CSS so I'm closing this.

**Closed by brunnre8** 2022-01-18 17:08 UTC
Labels: Type: Bug

**Comment by makeworld-the-better-one** [comment] 2022-01-18 18:24
In that case, the bug is that they are different sizes in the textbox and in sent messages. It should be consistent, no?
