### ISSUE TITLE
User messages disapear on channel with Auditorum mode

### ISSUE THREAD

**Issue by adamus1red** [thelounge/thelounge#3769] opened 2020-02-18 19:52 UTC
- _Node version:_ 12
- _Browser version:_ FireFox 73.0
- _Device, operating system:_ Windows 10
- _The Lounge version:_ 4.0.0

---

On a channel with UnrealIRCd's auditorium mode enabled user messages do not get displayed back to the user and appear to disapear into the void.

**Comment by xPaw** [comment] 2020-02-18 20:17
Enable raw traffic and show us the log of message that disappear.

https://thelounge.chat/docs/configuration#debugraw

**Comment by adamus1red** [comment] 2020-02-18 20:40
```
20:39 *** join #test2
20:39 *** @time=2020-02-18T20:39:07.820Z;msgid=yV9oNWkfxJvmC2HxGjabq5-2DMA27e4x+aUJg5aZERLUg :TEST1!~TEST1@DC186C70.CAB8F16F.1F789CD7.IP JOIN #test2 * :The Lounge User
20:39 *** MODE #test2
20:39 *** :teacup.lan 353 TEST1 = #test2 :TEST1!~TEST1@DC186C70.CAB8F16F.1F789CD7.IP @ChanServ!ChanServ@services.int
20:39 *** :teacup.lan 366 TEST1 #test2 :End of /NAMES list.
20:39 *** :teacup.lan 324 TEST1 #test2 +ntru
20:39 *** :teacup.lan 329 TEST1 #test2 1581989123
20:39 *** PRIVMSG #test2 test
20:39 *** PRIVMSG #test2 test2
```

View from the user side:
![image](https://user-images.githubusercontent.com/2502582/74776065-d0321c00-528e-11ea-9d4d-bb166ccf373b.png)

**Comment by xPaw** [comment] 2020-02-18 20:45
Is that with `echo-message` cap? If so, the server should reply with duplicate of the message which TL the can display.

**Closed** 2020-02-19 09:00 UTC
Labels: Type: Bug
