### ISSUE TITLE
Receive Notifications for All Messages on a Specified Channel

### ISSUE THREAD

**Issue by Trigex** [thelounge/thelounge#3714] opened 2020-01-19 20:01 UTC
### Feature Description

Some users (including myself) may want to be alerted on all messages on a given channel, especially in the case of a smaller channel with friends for example, but not receive notifications for all messages in every channel (That'd be endless!), thus, I request this be implemented ＿φ(￣ー￣ )

**Comment by xPaw** [comment] 2020-01-19 20:06
Duplicate of #85

**Closed by xPaw** 2020-01-19 20:06 UTC
Labels: Type: Feature
