### ISSUE TITLE
No support for /lastlog $username

### ISSUE THREAD

**Issue by Wetrain** [thelounge/thelounge#2104] opened 2018-02-23 14:24 UTC
Is there any news on supporting this command?

It replays the last log found from the given username?

**Comment by creesch** [comment] 2018-02-23 14:28
I am not sure `lastlog` is an irc standard. I do know that work is being done on logging everything to an slite database that can eventually be searched through the interface.

**Comment by Wetrain** [comment] 2018-02-23 14:32
@creesch Ah ok that would explain it, seems like a nice command though even for the standard.

**Comment by McInkay** [comment] 2018-02-23 14:45
We probably wouldn't build this into core (@thelounge/maintainers feel free to override me if you disagree) but we are slowly building a plugin system, and I think it would be a good feature for a plugin.

**Comment by xPaw** [comment] 2018-02-23 14:50
This can easily be done with a proper search system (e.g. #1529) after we merge sqlite logging. I'll close this as a duplicate of that.

**Closed by xPaw** 2018-02-23 14:50 UTC
