### ISSUE TITLE
ISO 8859-15 charset

### ISSUE THREAD

**Issue by klbz** [thelounge/thelounge#2691] opened 2018-08-04 09:24 UTC
Cannot join channel's that were made back in ISO 8859 and contains scandic letters like Ä or Ö. Irssi supports this with /eval: \344 being Ä and \366 being Ö.

Irssi example: /eval /join #\344\344kk\366nen

**Comment by xPaw** [comment] 2018-08-04 09:26
Duplicate of #1094 or #371. It all boils down to the fact that Lounge is an UTF8 only client.

**Closed by xPaw** 2018-08-04 09:26 UTC
