### ISSUE TITLE
Randomly occurring crashes due to unhandled error in events.js

### ISSUE THREAD

**Issue by ctlaltdefeat** [thelounge/thelounge#3200] opened 2019-05-05 01:57 UTC
* *Node version:* 11.15.0
* *Browser version:* (server-side issue)
* *Device, operating system:* Arch Linux x64
* *The Lounge version:* 3.0.1-1

---

Every few hours, the Lounge crashes with only this showing up in the logs:

```
May 05 03:31:00 archlinux-latest-64-minimal thelounge[19843]: events.js:170
May 05 03:31:00 archlinux-latest-64-minimal thelounge[19843]:       throw er; // Unhandled 'error' event
May 05 03:31:00 archlinux-latest-64-minimal thelounge[19843]:       ^
May 05 03:31:00 archlinux-latest-64-minimal thelounge[19843]: Error: read ECONNRESET
May 05 03:31:00 archlinux-latest-64-minimal thelounge[19843]:     at TCP.onStreamRead (internal/stream_base_commons.js:167:27)
May 05 03:31:00 archlinux-latest-64-minimal thelounge[19843]: Emitted 'error' event at:
May 05 03:31:00 archlinux-latest-64-minimal thelounge[19843]:     at emitErrorNT (internal/streams/destroy.js:91:8)
May 05 03:31:00 archlinux-latest-64-minimal thelounge[19843]:     at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
May 05 03:31:00 archlinux-latest-64-minimal thelounge[19843]:     at processTicksAndRejections (internal/process/task_queues.js:81:17)
```

Any idea how I would go about debugging this?

**Comment by xPaw** [comment] 2019-05-10 12:00
First of all, try upgrading your Node and see if it still occurs.

**Comment by ctlaltdefeat** [comment] 2019-05-10 13:56
Sorry, I accidentally specified my npm version rather than node for some reason. I have v11.15.0.
By the way, I tried using the debug options in the the Lounge's config. Nothing relevant shows up before the block I pasted above.

**Comment by xPaw** [comment] 2019-05-10 14:06
Right. Well we can't really do anything with the provided information because the stacktrace is all Node internal code.

**Comment by ctlaltdefeat** [comment] 2019-05-10 14:13
My internet connection seems fine (other applications remain connected through this), but perhaps it's possible to reproduce this error by disconnecting from the internet? In this case, maybe it's worth having some error-handling logic that doesn't cause the service to crash?

**Comment by xPaw** [comment] 2019-05-10 14:14
Lounge already has all the relevant error handling in place, if what you described was a thing there would be more than one report about it.

**Comment by ctlaltdefeat** [comment] 2019-05-10 14:16
Weird. Well, I did try some TCP-related sysctl tuning yesterday and since then there have been no crashes, so I hope that continues. 
If I can supply other info let me know, and feel free to close this if you don't think this issue can be further progressed.

**Comment by xPaw** [comment] 2019-05-10 14:17
Realistically we can't do anything about this issue without a solid reproduction case so anyone else could try to trigger the error themslves.

**Comment by xPaw** [comment] 2019-05-13 07:34
I will close this for now. Feel free to reopen if you get more information that can help us reproduce and/or fix this.

**Closed by xPaw** 2019-05-13 07:34 UTC

**Comment by xPaw** [comment] 2019-06-10 10:06
Probably related: https://github.com/nodejs/node/issues/23169
