### ISSUE TITLE
View Channel mode

### ISSUE THREAD

**Issue by McInkay** [thelounge/thelounge#341] opened 2016-05-19 09:14 UTC
We don't seem to handle viewing channel modes.

When you do `/mode #channel` you don't get the list of modes, you get nothing. Looking at the code, this seems to be that we [return when we only have 1 argument](https://github.com/thelounge/lounge/blob/master/src/plugins/inputs/mode.js#L18) rather than sending a mode command with no mode.

**Comment by YaManicKill** [comment] 2016-05-19 09:16
Duplicate of #223

**Comment by xPaw** [comment] 2019-03-07 10:55
Closing as duplicate of #885

**Closed by xPaw** 2019-03-07 10:55 UTC
Labels: Status: Duplicate
