### ISSUE TITLE
Custom CSS only syncs across clients when they're open

### ISSUE THREAD

**Issue by Jay2k1** [thelounge/thelounge#2278] opened 2018-03-22 19:48 UTC
* *Node version: 6.11.3* 
* *Browser version: many* 
* *Device, operating system: many* 
* *The Lounge version: 453eab3* 

---

Have one client open and change your custom CSS, then open another (like when you come home from work), your changes won't be there. 

Edit custom CSS while another client is open though and it gets the changes.

You'd expect it to work even when changes were made while other clients were closed.

**Comment by xPaw** [comment] 2018-03-22 19:50
I can confirm it doesn't apply new settings from the server when opening a second client (at least with CSS).

@creesch mind looking?

**Comment by McInkay** [comment] 2018-03-23 08:24
I think we ended up discussing this on IRC when it was merged, did we not figure out a fix? Maybe I misremember, and we didn't, but maybe it has been reverted?

**Comment by creesch** [comment] 2018-03-23 09:50
Uh this sounds like regression somewhere because this is something I did test. 
I'll have a look. 

@McInkay the thing we discussed on irc has to do with clients loosing connection and then not syncing on reconnect. Also something I'll have a look at.

**Comment by McInkay** [comment] 2018-03-23 09:59
> @McInkay the thing we discussed on irc has to do with clients loosing connection and then not syncing on reconnect. Also something I'll have a look at.

Ah yes, my bad. Thanks for looking into these.

**Closed** 2018-04-11 05:30 UTC
Labels: Type: Bug
