### ISSUE TITLE
Channel search

### ISSUE THREAD

**Issue by MaxLeiter** [thelounge/thelounge#1289] opened 2017-06-30 21:23 UTC
Users should be able to search their current channels (i.e. like user searching, but on the channel sidebar) (Gitter, Discord, Messenger, etc. all support it/the equivalent of channels).

Will require a UI tweak, possibly somewhat major.

**Comment by dgw** [comment] 2017-06-30 21:27
Channel search as in what `/list` does with parameters on some networks (or messaging ALIS on freenode)? Or searching/filtering the list of channels joined, like how user filtering works?

**Comment by MaxLeiter** [comment] 2017-06-30 21:32
Sorry for not being clear - like user filtering. I updated the description.

**Comment by xPaw** [comment] 2018-07-18 12:01
Practically a dupe of #1454?

**Closed** 2019-01-16 09:44 UTC
