### ISSUE TITLE
Support connection through an http proxy

### ISSUE THREAD

**Issue by michael-thayer-vb** [thelounge/thelounge#2602] opened 2018-06-28 08:00 UTC
Currently the Lounge does not seem to be able to connect to an IRC server on the other side of a proxy (e.g. a corporate proxy).  On Linux and similar systems the lowest effort way of supporting this is usually through the http_proxy variable.  It would be great if the Lounge could handle that.  Whether this is best fixed in the Lounge or elsewhere, if it is something you are not likely to find time for soon I would be grateful for pointers to the right framework and the code: I have never used either node.js nor JavaScript previously, so that would speed me up; and even if the right place is in an external framework you might have some idea of where to look.

**Comment by xPaw** [comment] 2018-06-28 08:02
Duplicate of #1375

**Closed by xPaw** 2018-06-28 08:02 UTC
