### ISSUE TITLE
Charmap ISSUE - mIRC to Web and Web to mIRC problem

### ISSUE THREAD

**Issue by TuSuNaMi** [thelounge/thelounge#1094] opened 2017-04-27 14:48 UTC
Hello this is my problem,

IRC server inspircd 2.0

Any oppinions?

![problem](https://cloud.githubusercontent.com/assets/2782969/25489161/aa3f1648-2b71-11e7-9d3c-6a4331ca11f5.png)

**Comment by astorije** [comment] 2017-04-27 22:46
We had #987 opened some time ago that didn't make it, but I'm not sure what are the plans for this.

**Comment by metsjeesus** [comment] 2017-05-01 21:51
@astorije its same thing what i figured out. Encodings help a bit, but not completely. There is no iconv setting what converts it correctly.

**Comment by TuSuNaMi** [comment] 2017-05-10 10:28
Any plan for solve this?

**Comment by astorije** [comment] 2017-05-10 17:20
I don't believe any maintainers will be prioritizing this themselves. Open to contributions though.

**Comment by metsjeesus** [comment] 2017-05-10 17:43
I will do it asap, if there is a way to implement it. One option is to wait if iconv or irc-framework chooses to make or include a iso-8859-1/utf8 multibyte encoder, other way is to use my monky patch what does same thing. I dont know if there a third way, if there is, im up to make it.

**Comment by christer88** [comment] 2017-06-12 12:29
Agree with TuSuNaMi. This is something that should be fixed since it's that annoying meeting a person with a bunch of ?, and yes, it happens.. reguarly. It's also something that is fixed in both mIRC and other clients.

**Comment by lorkki** [comment] 2018-04-01 17:08
I left a pull request at irc-framework, which seemed like the most correct place to fix it: https://github.com/kiwiirc/irc-framework/issues/7

I suppose I should follow up with another one here, to add configuration options?

**Comment by xPaw** [comment] 2019-03-07 10:49
Closing as a duplicate of https://github.com/kiwiirc/irc-framework/issues/7 and https://github.com/thelounge/thelounge/issues/371

**Closed by xPaw** 2019-03-07 10:49 UTC
Labels: Type: Bug, help wanted
