### ISSUE TITLE
Thelounge character error

### ISSUE THREAD

**Issue by ircalem** [thelounge/thelounge#2204] opened 2018-03-12 15:26 UTC
How can I change the character of Thelounge (iso-8859-9)

http://www.imgim.com/8763incit3310126.png

**Comment by xPaw** [comment] 2018-03-12 15:33
Duplicate of #1094

**Closed by xPaw** 2018-03-12 15:33 UTC

**Comment by ircalem** [comment] 2018-03-12 16:45
he could not solve the problem,

iso-8859-9 character i have to do .

**Comment by xPaw** [comment] 2018-03-12 16:48
Yes the problem is not solved, hence why it's a duplicate issue.

**Comment by ircalem** [comment] 2018-03-12 19:50
how can you get rid of this problem ?
