### ISSUE TITLE
Ignore should allow wildcards in all fields

### ISSUE THREAD

**Issue by khaytsus** [thelounge/thelounge#3891] opened 2020-04-30 14:22 UTC
I'm not sure what other limitations there are, but the nick field I've noticed does not appear to support a wildcard, such as ignoring 'nick*' where a nick is randomly nick1 nick_away nick_BLAH etc.  In cases where an ident and/or hostmask aren't possible, I fall back on nicks, but not being able to ignore using a wildcard in a nick is pretty limited.  I don't want to ignore every random variation some users go through.

I haven't noticed yet, but if ident and hostname also have this limitation they should also be updated.

**Comment by jmcgnh** [comment] 2020-04-30 14:35
Are you speaking of the /ignore command? That's not interpreted by theLounge, it's a function of the underlying IRC server and its protocols and theLounge just passes it through.

**Comment by khaytsus** [comment] 2020-04-30 14:37
Yes, in the ignore command.  I wasn't aware there was a universal server-side ignore type protocol, is there any way to do this that I am missing?

**Comment by xPaw** [comment] 2020-04-30 14:43
> Are you speaking of the /ignore command? That's not interpreted by theLounge, it's a function of the underlying IRC server and its protocols and theLounge just passes it through.

That's not true, it's a TL command.

**Comment by xPaw** [comment] 2020-04-30 14:44
Duplicate of #2573

**Comment by khaytsus** [comment] 2020-04-30 14:45
> Duplicate of #2573

Except that one has turned into such a large thing that nobody wants to touch it, including matching message patterns, etc.

**Closed** 2020-04-30 14:44 UTC
Labels: Type: Feature
