### ISSUE TITLE
prefetch broken on lastest nodejs

### ISSUE THREAD

**Issue by dateno1** [thelounge/thelounge#2789] opened 2018-09-21 05:25 UTC
* *Node version:* nodejs 8.60 and more newer
* *Browser version:* firefox 62.0 x64
* *Device, operating system:* client : windows 10 x64/server : linux x64
* *The Lounge version:* 2.7.1
---
image prefetch not work with new version nodejs
![pre](https://user-images.githubusercontent.com/12645246/45861931-5d2b2a00-bdaa-11e8-8aca-02738dad5ad9.png)
like this (not prepetched and havn't petch button)

![n](https://user-images.githubusercontent.com/12645246/45862333-3ec62e00-bdac-11e8-923e-11164034d082.png)
with nodejs v8.5.0

nodejs 8.5.0 and old version worked well
nodejs 8.6.0 and new version not worked

all nodejs binary downloaded from [https://nodejs.org/en/download/releases ](https://nodejs.org/en/download/releases )

command
**lounge start
nodejs --max-old-space-size=1024 /usr/lib/node_modules/thelounge/index.js start
node-v8.6.0-linux-x64/bin/node --max-old-space-size=1024 /usr/lib/node_modules/thelounge/index.js start**
same result

work with
**node-v8.5.0-linux-x64/bin/node --max-old-space-size=1024 /usr/lib/node_modules/thelounge/index.js start**

image size is 6mb and limit is 10240k

install thelounge with npm and yarn but same result

**Comment by fnutt** [comment] 2018-09-21 05:47
Considering you're using 2.7.1 and there's been a rewriting of over half of the code in 3.1 (vue branch), I think it would be nice if you could test to see if the issue is still in vue branch.

How to test 3.1 vue branch:
(1) cd to somewhere you want the folder
(2) git clone https://github.com/thelounge/thelounge.git
(3) cd thelounge
(4) git checkout vue
(5) yarn install
(6) NODE_ENV=production yarn build

To start it, stay in the /thelounge/ folder and type yarn start.

**Comment by xPaw** [comment] 2018-09-21 05:49
Can you try latest the lounge RC?

**Comment by xPaw** [comment] 2018-09-21 08:08
Closing this because I suspect this to be fixed by #2159.

@dateno1 If you still have issues on 3.0.0-rc.1, feel free to re-open the issue.

**Closed by xPaw** 2018-09-21 08:08 UTC

**Comment by dateno1** [comment] 2018-09-21 10:36
> 
> 
> Can you try latest the lounge RC?

not yet

i don't want to service with not stable version

i will waiting new stable version

i want to you are test that with lastest version nodejs before release

**Comment by xPaw** [comment] 2018-09-21 10:36
> i want to you are test that with lastest version nodejs before release

I already use latest node version, and it works fine.

**Comment by dateno1** [comment] 2018-09-21 10:51
> 
> 
> Considering you're using 2.7.1 and there's been a rewriting of over half of the code in 3.1 (vue branch), I think it would be nice if you could test to see if the issue is still in vue branch.
> 
> How to test 3.1 vue branch:
> (1) cd to somewhere you want the folder
> (2) git clone https://github.com/thelounge/thelounge.git
> (3) cd thelounge
> (4) git checkout vue
> (5) yarn install
> (6) NODE_ENV=production yarn build
> 
> To start it, stay in the /thelounge/ folder and type yarn start.

thanks it work with 3.0.0-RC.1 :)
