### ISSUE TITLE
Another Feature Request: Image Uploader

### ISSUE THREAD

**Issue by TheDetectiveTaco** [thelounge/thelounge#2507] opened 2018-06-03 18:56 UTC
Something that would be nice that is an image uploader in thelounge page. Or even better being able to use my own image uploader on my webserver. So I can just click the button and just upload an image and get it right in the app. Would be even better being able to use the image uploader on my own webserver.

**Comment by xPaw** [comment] 2018-06-03 18:57
Duplicate of #1679. Please use search.

**Closed by xPaw** 2018-06-03 18:57 UTC
