### ISSUE TITLE
DM window should follow nick changes

### ISSUE THREAD

**Issue by linuxkidd** [thelounge/thelounge#2726] opened 2018-08-27 21:43 UTC
**Reproduction steps:**
1. Start a 'direct message' conversation with someone
2. Have that other part change their nick
3. Attempt to send a message in the existing 'direct message' window

**Observed results:**
 - Message send fails on 'no such user/channel'
 - 'direct message' window title still reflects old nick

**Desired / Expected results:**
 - 'direct message' window title changes to reflect the other users new nick
 - Messages to the user after their nick change should go to the user with the new nick

**Comment by xPaw** [comment] 2018-08-27 21:46
Duplicate of #337

**Closed by xPaw** 2018-08-27 21:46 UTC
