### ISSUE TITLE
Consider server connection as secure if the server IP address is a private address

### ISSUE THREAD

**Issue by timdream** [thelounge/thelounge#4027] opened 2020-08-12 04:54 UTC
### Feature Description

I would like to propose a feature where the server connection is considered secure (without warning etc.) when the server IP address is a private address.

Use case: I've setup a the lounge docker instance connecting to an IRC server defined on the same `docker-compose` file. Docker creates a whole isolated network stack for the two instances and the lounge simply connects to the server with the container hostname, i.e. `ircd:6667` — see [Networking in Compose](https://docs.docker.com/compose/networking/). Since the hostname is not a FQDN, I won't be able to give it a proper certificate and make the connection secure. The whole secure connection exercise is moot too, since it's simply a connection b/t two docker containers.

I therefore thinks the lounge can be smarter and show the connection as secure when connecting to a local IRC server.

**Comment by brunnre8** [comment] 2020-08-12 05:08
Hosting something on localhost doesn't magically make an invalid ssl cert valid.

The Lounge should not try  to guess in what environment it is running in my opinion.

If you want a cert to be trusted add ithe signing CA to the CA store on the container.

By your reasoning you might as well just use plain text, then the warning goes away as well

**Comment by fnutt** [comment] 2020-08-12 06:23
`#sidebar .channel-list-item[data-type="lobby"],
#sidebar .not-secure .channel-list-item[data-type="lobby"] {
    color: <your choice of colour>;
}

#sidebar .channel-list-item[data-type="lobby"] .add-channel:not(.opened),
.not-secure-tooltip,
.not-secure-icon {
    display: none;
}`

**Comment by xPaw** [comment] 2020-08-12 06:55
We follow what browsers do and only consider actually localhost connections without TLS secure.

What @brunnre8 is saying applies too.

Closing as this works as intended.

**Closed by xPaw** 2020-08-12 06:55 UTC
Labels: Type: Feature

**Comment by timdream** [comment] 2020-08-12 21:43
Understood. Thanks for the response.
