### ISSUE TITLE
TypeError: log.warn is not a function

### ISSUE THREAD

**Issue by simpleauthority** [thelounge/thelounge#2706] opened 2018-08-18 20:34 UTC
* *Node version:* 8.11.3
* *Browser version:* Chrome Version 68.0.3440.106 (Official Build) (64-bit)
* *Device, operating system:* Windows 10
* *The Lounge version:* 3.0.0-pre.7

---

```
lounge@webserver:/$ thelounge start
/usr/lib/node_modules/thelounge/src/helper.js:126
                        log.warn(`The default theme ${colors.red("example")} was renamed to ${colors.green("default")} as of The Lounge v3.`);
                            ^

TypeError: log.warn is not a function
    at Object.setHome (/usr/lib/node_modules/thelounge/src/helper.js:126:8)
    at Object.<anonymous> (/usr/lib/node_modules/thelounge/src/command-line/index.js:35:8)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/thelounge/index.js:38:1)
```

**Comment by xPaw** [comment] 2018-08-18 20:36
Duplicate of #2568. Please use search.

**Closed by xPaw** 2018-08-18 20:36 UTC
Labels: Status: Duplicate

**Comment by simpleauthority** [comment] 2018-08-18 20:38
my bad
