### ISSUE TITLE
'Enter' on user in userlist opens context menu, which isn't focused

### ISSUE THREAD

**Issue by MaxLeiter** [thelounge/thelounge#2322] opened 2018-04-01 00:19 UTC
Using enter on a user in the userlist opens a context menu for that user (as a click would), however, the focus isn't shifted to the context menu and remains on the userlist.

if the above doesn't make sense try using just the keyboard to open a query with a user on the userlist

**Comment by xPaw** [comment] 2018-04-01 07:58
Duplicate of #1911

**Closed by xPaw** 2018-04-01 07:58 UTC
