### ISSUE TITLE
Scroll to top/first unread message

### ISSUE THREAD

**Issue by sfkpmr** [thelounge/thelounge#4172] opened 2021-03-02 19:32 UTC
### Feature Description

As it is now you need to scroll up and then hit "show older messages" over and over, until you get to where you were when you last read something. Not practical with busy channels.

Would be nice to be able to hit a button to go back to where you were when you left.

**Comment by xnaas** [comment] 2021-03-02 19:33
This is a duplicate of #849.

**Closed** 2021-03-02 19:58 UTC
Labels: Type: Feature

**Comment by MaxLeiter** [comment] 2021-03-02 20:10
@sfkpmr The 'show older messages' should automatically be triggered when you scroll up since v2.5.0. Is this not happening for you?

**Comment by sfkpmr** [comment] 2021-03-02 20:39
It is, but I can't see a way to immediately go to the first message, I need to scroll through everything in between.
