### ISSUE TITLE
Visually identify Away or Idle Users in User List

### ISSUE THREAD

**Issue by briandoll** [thelounge/thelounge#4301] opened 2021-08-31 19:08 UTC
### Feature Description

IRC is great for synchronous conversations, and thanks to various _persistent_ clients (and similar solutions), it can be great for async chat as well. A side effect of these persistent clients (TheLounge being a good example), is that channels may have many users in them who are away or have been idle for a long time. Idle users are not a problem exactly, however, it would be nice to know which users in a room are relatively active, at a given time. 

Currently, one might run `whois` on a user to check how long they've been idle to see if they're around for a chat. This is possible today, but must be done user by user.

It would be great if it were possible for the User List in TheLounge to differentiate "active" vs. "inactive" users in a channel. Themes could decide how to display this differentiation (ie. greying them out, muting their color, or even separating the User List into an Active and Inactive list), but it would be incredibly handy to be in a channel and see immediately who's actually around vs. who's away or idle.

**Comment by MaxLeiter** [comment] 2021-08-31 19:14
Thanks for the issue! But closing as dupe of https://github.com/thelounge/thelounge/issues/872

**Closed by MaxLeiter** 2021-08-31 19:14 UTC
Labels: Type: Feature
