### ISSUE TITLE
Pinned channels in sidebar

### ISSUE THREAD

**Issue by KlaasT** [thelounge/thelounge#2968] opened 2019-01-09 14:31 UTC
### Feature Description

Would it be possible to have an option to have some "pinned channels" in the sidebar which can be defined using the configuration? So you could suggest to the user to follow the #help channel or some others which could be joined by just clicking on them.

I think that would make things easier for IRC newbies.

Thanks.

**Comment by xPaw** [comment] 2019-01-16 09:42
Your problem would be partially solved by using predefined channels (defaults.join) so users automatically join these channels when connecting.

As for pinning in the sidebar, I will close this as a duplicate of #180

**Closed by xPaw** 2019-01-16 09:42 UTC
