### ISSUE TITLE
UI: pick the side of network panel (side and top)

### ISSUE THREAD

**Issue by mzelenka** [thelounge/thelounge#4100] opened 2020-11-08 14:51 UTC
Sometimes network tab is using too much space and you need to move it away so you could lets say type from your mobile device but... you wont be able to see tabs for new messages (to switch users) unless you open network tab again.

If you could implement something like this (old kiwi client):

![Screenshot_7](https://user-images.githubusercontent.com/53977501/98468285-1f7ffa00-21da-11eb-8057-d68dc2e990f9.jpg)

**Comment by MaxLeiter** [comment] 2022-04-12 01:16
Closing as a dupe of https://github.com/thelounge/thelounge/issues/3736

**Closed by MaxLeiter** 2022-04-12 01:16 UTC
Labels: Type: Feature
