### ISSUE TITLE
Channel reop list (mode +R) cannot be seen using The Lounge

### ISSUE THREAD

**Issue by Mikaela** [thelounge/thelounge#3701] opened 2020-01-15 18:49 UTC
- _Node version:_ v12.14.0
- _Browser version:_ Firefox Beta 73.0b5 (64-bittinen)
- _Device, operating system:_
  - Server: Debian GNU/Linux 9.11 (stretch)
  - Client: Debian GNU/Linux bullseye/sid
- _The Lounge version:_ 4.0.0-1

---

When I run `/mode #channel +I` or `+b` I get a new tab listing the invites/bans/similar, when I run `/mode +R`, I see no output without `debug.raw` while I expect to see channel reop list in the same format.

Example raw output:

```
20:44:01 *** :irc.atw-inter.net 344 Mikaela #channel *!*@*.mikaela.info
20:44:01 *** :irc.atw-inter.net 345 Mikaela #channel :End of Channel Reop List
20:44:01 [345]#channel End of Channel Reop List 
```

It also seems like `+e`, channel ban exception list doesn't open in a new tab, but it seems to be visible in the server tab without `debug.raw`.

**Comment by xPaw** [comment] 2020-01-16 13:14
Duplicate of #2827, feel free to comment with the extra modes that require list treatment.

**Closed by xPaw** 2020-01-16 13:14 UTC
Labels: Type: Bug
