### ISSUE TITLE
Remove help/settings after hitting it again

### ISSUE THREAD

**Issue by KwadroNaut** [thelounge/thelounge#1220] opened 2017-06-12 13:05 UTC
When arriving at a 'lounge', hitting the settings or help before joining a channel leaves you with an unusable interface. ![lounge](https://user-images.githubusercontent.com/99527/27035122-7ad0e84a-4f80-11e7-9a06-7cba8564104c.png)
I expect to be able to hit (esc), find some X to click or when clicking 'help' again that it dissapears and I get back to the user preferences window to add channel and network.

**Comment by YaManicKill** [comment] 2017-06-12 13:17
Good catch, this is why I had wanted the help window to be a modal, fwiw, @thelounge/maintainers as we wouldn't have this issue. 

@KwadroNaut In the meantime, you can click the browser back button to get back to that, but I agree we need another fix for this.

Possible options:

1. Add a button for the initial page for adding network on this page (we appear to not have it here, but on every other page we do)
2. Turn it into a modal so you can esc or click off it to hide it (my preferred option)
3. Just add an "x" in the top right of this window that essentially clicks back

Thoughts?

**Comment by dgw** [comment] 2017-06-12 13:38
Making it a modal makes the most sense. Other apps I've seen with help dialogs, like Gmail, do so. Right here on Github, if you type <kbd>?</kbd> outside of an input field, you get a modal dialog with the keyboard shortcuts.

**Comment by xPaw** [comment] 2017-06-12 13:42
Where's the `+` button on your screenshot? Clicking that would bring you back to connect window.

![12-134103088](https://user-images.githubusercontent.com/613331/27036616-15586228-4f8e-11e7-80a5-fd052d9c15f6.png)

**Comment by KwadroNaut** [comment] 2017-06-12 13:58
Someone removed that intentionally in the gateway I tried. I didn't know. It adds a second network connection and doesn't simply add 1 channel. Making it modal would be much appreciated.

**Comment by xPaw** [comment] 2017-06-12 13:59
Basically this is not a bug, but going to previous window when clicking the button twice might be of use.

**Comment by astorije** [comment] 2017-06-12 16:09
Making it a modal would not solve it. Sure, it would hide the issue for the Help page, but the issue would remain for the settings or any other window we could make like that.
UX-wise, modals are reasonable when they are context-dependent. If the Help window was showing content based on where the user is (like in GitHub), then yes, a modal would make sense.

> but going to previous window when clicking the button twice might be of use.

It might, but I can see how this could be unexpected, especially for users with motor disabilities. Another option could be a "Back" button at the top left of Settings / Help pages. It could just say "Back" or "Back to <channel, query, window>" with context, useful on these 2 long pages, especially for people affected by cognitive disorders.

As for the original issue, if <kbd>+</kbd> was intentionally hidden by your administrator, there is nothing we can do ourselves.

**Comment by HartS** [comment] 2017-09-29 20:48
Many apps (slack, hipchat, github) provide a shortcut (usually ctrl+/ or shift+/) to toggle the list of keyboard shortcuts. I personally find this convention helpful. In all of those examples, this help window is a modal as well, though the important thing is that the help window can be disabled/removed and any other state is preserved.

**Comment by xPaw** [comment] 2019-12-20 10:27
I'm closing this because we're unlikely to change the current behaviour (that clicking the button doesn't hide it).

**Closed by xPaw** 2019-12-20 10:27 UTC
Labels: Type: Feature
