### ISSUE TITLE
Topic autocomplete

### ISSUE THREAD

**Issue by eloydegen** [thelounge/thelounge#3261] opened 2019-06-15 20:38 UTC
### Feature Description
In `irssi`, I can autocomplete the topic by entering `/topic<space><tab>`, so I can change it without copy pasting. I would like to request something alike this in thelounge.

**Comment by FryDay** [comment] 2019-10-05 19:21
I'll take a look at this.

**Comment by xPaw** [comment] 2019-12-20 10:28
Duplicate of #2513

**Closed by xPaw** 2019-12-20 10:28 UTC
Labels: Type: Feature
