### ISSUE TITLE
writing connection/disconnection inside private chat

### ISSUE THREAD

**Issue by Nek-** [thelounge/thelounge#3747] opened 2020-02-07 21:00 UTC
### Feature Description

I know you already think about having an icon with ppl status directly in navbar (https://github.com/thelounge/thelounge/issues/872). I also know you did that: https://github.com/thelounge/thelounge/pull/3494

But what about adding messages - **without notice** - inside conversations that says "xxx disconnected at xx:xx" and "xxx is back at xx:xx".

 :+1: to agree :-1: to disagree, please vote as team leader :) .

**Comment by xPaw** [comment] 2020-02-07 21:04
Duplicate of #337

**Closed by xPaw** 2020-02-07 21:04 UTC
Labels: Type: Feature
