### ISSUE TITLE
Crash when TL can't read a user config

### ISSUE THREAD

**Issue by Jay2k1** [thelounge/thelounge#2128] opened 2018-02-28 00:35 UTC
When you remove read permissions from a user config file while TL is running, it crashes with
```
fs.js:642
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EACCES: permission denied, open '/home/Jay2k1/.lounge/users/foobar.json'
    at Error (native)
    at Object.fs.openSync (fs.js:642:18)
    at Object.fs.readFileSync (fs.js:510:33)
    at readUserConfig (/home/Jay2k1/lounge/src/clientManager.js:189:18)
    at ClientManager.loadUser (/home/Jay2k1/lounge/src/clientManager.js:72:21)
    at updatedUsers.forEach (/home/Jay2k1/lounge/src/clientManager.js:57:39)
    at Array.forEach (native)
    at FSWatcher.fs.watch._.debounce (/home/Jay2k1/lounge/src/clientManager.js:57:16)
    at invokeFunc (/home/Jay2k1/lounge/node_modules/lodash/lodash.js:10325:23)
    at trailingEdge (/home/Jay2k1/lounge/node_modules/lodash/lodash.js:10374:18)
``` 
@astorije suggested just issuing a warning instead.

**Comment by astorije** [comment] 2018-02-28 00:40
A warning and ignore the file, or just ignore the file.
Either way, if read permissions are removed while TL is running, it should remove the user from the system (and more importantly, not crash 😅).

**Comment by xPaw** [comment] 2018-02-28 08:16
This is *pretty much* a duplicate of #447 as it would be caused within the same function.

**Closed** 2018-03-03 21:03 UTC
Labels: Type: Bug
