### ISSUE TITLE
Show messages sent with /msg in a query window 

### ISSUE THREAD

**Issue by dgw** [thelounge/thelounge#1127] opened 2017-05-02 01:33 UTC
Access-filtered channel messages don't work properly. Examples:

* Sending `/msg @#channel test` appears nowhere in The Lounge.
* Incoming messages to `@#channel` appear in a query buffer, not the channel buffer.

**Comment by xPaw** [comment] 2017-05-02 06:54
Both of these were somewhat by design. `/msg` into an unknown target does not create a channel.
Incoming `@#` messages create a separate window to avoid mistakenly sending OP stuff into normal channel.

**Comment by dgw** [comment] 2017-05-02 07:12
It's inconsistent with normal client behavior, though. Every other client I've used displays both incoming and outgoing `@#` (and others, like `+#` or `%#`) messages in the channel buffer with everything else. Ignoring the outgoing messages in the UI is especially strange and counter-intuitive.

**Comment by YaManicKill** [comment] 2017-06-30 10:41
I've marked this as a bug because I agree that outgoing messages should show up somewhere.

I think we should probably show messages sent with "/msg". I get that it's not an irc thing that most clients do, but I think people expect this nowadays.

As for messages being in a different window than the main window, I definitely agree that should stay. Showing messages in a channel that not everyone can see is confusing, and I have seen it cause many issues for people.

**Comment by dgw** [comment] 2017-10-14 02:21
\*ponders tackling this while it's still Hacktoberfest\*

Shouldn't be _too_ hard to capture the `/msg` command and send its contents to a window, right?

(Right?)

:rofl:

**Comment by xPaw** [comment] 2019-10-24 13:50
Is this still an issue?

statusmsg have been correctly handled by putting messages in the channel for a while now.

**Comment by McInkay** [comment] 2019-10-28 10:09
Testing this, it looks like we now open a query window on `/msg` and put the message there. So yeah, this is fixed.

(insert arguments about whether it was the right fix or not)

**Closed by McInkay** 2019-10-28 10:09 UTC
Labels: Type: Bug
