### ISSUE TITLE
Slow typing response

### ISSUE THREAD

**Issue by lcarva** [thelounge/thelounge#4039] opened 2020-08-20 13:22 UTC
- _Node version:_ v12.18.3
- _Browser version:_ Version 84.0.4147.125 (Official Build) (64-bit)
- _Device, operating system:_ Fedora 31 (Linux localhost.localdomain 5.7.15-100.fc31.x86_64 #1 SMP Tue Aug 11 17:18:01 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux)
- _The Lounge version:_ v4.1.0

---

When I type a message, there's a really long delay between hitting the key and the character being displayed on the screen. The faster I type the slower it gets.

I'm using the `docker.io/thelounge/thelounge:latest` (`sha256:f4b6e0831190b35596fb16bb3c683695338ed9a4ad5b4038270ea7f0430cba2a`) image to host the server.

The profiler looks like this:
![image](https://user-images.githubusercontent.com/5272931/90775022-4e1ac280-e2c6-11ea-8d33-2ac11442a22d.png)

![image](https://user-images.githubusercontent.com/5272931/90775229-9934d580-e2c6-11ea-9595-2baebc0f5ed4.png)

![image](https://user-images.githubusercontent.com/5272931/90775299-ae116900-e2c6-11ea-933e-63bfdacc40cd.png)

**Comment by Jay2k1** [comment] 2020-08-20 13:24
Duplicate of #4018

**Closed** 2020-08-20 13:24 UTC
Labels: Type: Bug
