### ISSUE TITLE
Emoji list 

### ISSUE THREAD

**Issue by siniStar7boy** [thelounge/thelounge#4566] opened 2022-05-06 18:18 UTC
### Feature Description
It would be extremely helpful to have an Emoji list for users who cannot remember the :emoji-name: 

IRCCloud has an emoji list, for example -- in the input/typing area where you can select the desired one and it is put into the message.

On IRC (Libera.Chat), this was requested by both @freakyy85 and myself.

**Comment by aab12345** [comment] 2022-05-06 18:19
There is one -

https://github.com/thelounge/thelounge/blob/24316fc304d339d07ff15771fcde4c132cd9bb4c/client/js/helpers/simplemap.json

**Comment by dgw** [comment] 2022-05-06 18:20
@aab12345 That's not accessible by a user via the GUI.

**Comment by freakyy85** [comment] 2022-05-06 18:22
Yes it would be really nice to have this. :)

**Comment by xPaw** [comment] 2022-05-11 10:54
Duplicate of #3958

**Closed** 2022-05-11 11:27 UTC
Labels: Type: Feature
