### ISSUE TITLE
Socket.io Timeouts - WebSocket is already in CLOSING or CLOSED state.

### ISSUE THREAD

**Issue by keybrdist** [thelounge/thelounge#4111] opened 2020-11-25 15:28 UTC
- _Node version:_ latest
- _Browser version:_ Chrome and Safari only (not affecting Firefox)
- _Device, operating system:_ OSX and Windows
- _The Lounge version:_ latest

---
Is is possible to override the default pingTimeout for socket.io?

1. thelounge is disconnecting within 1-3 minutes when the browser tab is not in the foreground, and it is due to an issue with socket.io.  I have found that this issue has been raised on socketio's github. They are saying it appeared in socketio ~ v2.0.3 and is supposed to be fixed in v3.0.3  https://github.com/socketio/socket.io/issues/3259

2. As a work-around I would like to set the timeout value to a higher number.
https://github.com/socketio/socket.io/issues/3259#issuecomment-448058937. Is it possible to set the default socketio timeout via thelounge config or some other means without forking the project?

**Comment by xPaw** [comment] 2020-11-25 15:39
Closing as duplicate of #4108.

I will upgrade socket.io though.

**Closed by xPaw** 2020-11-25 15:39 UTC
Labels: Type: Bug
