### ISSUE TITLE
Add OS fallback fonts so that emoji can render

### ISSUE THREAD

**Issue by xPaw** [thelounge/thelounge#1128] opened 2017-05-02 09:48 UTC
On Windows 7 with default theme, emoji do not render.

**Comment by MiniDigger** [comment] 2017-05-02 10:30
which browser? can't reproduce on chrome (just cleanly install win10, so no theme)

**Comment by xPaw** [comment] 2017-05-02 10:53
Looks like Windows 7 doesn't have updated fonts to render all emoji, so I don't think we can do anything about it. Unless we suggest downloading a full emoji font (like EmojiOne) and adding a fallback to that.

**Comment by MaxLeiter** [comment] 2017-10-25 21:08
Is this fixed now/still valid?

**Closed** 2018-07-18 11:55 UTC
Labels: Type: Bug

**Comment by richrd** [comment] 2018-07-18 22:07
I know this is closed, but I have the same "issue" on Chromium on Kubuntu. Is there something I can do locally to fix that?

**Comment by McInkay** [comment] 2018-07-19 06:59
What version are you on, @richrd ? I believe Ubuntu added colour emoji for 18.04. Not sure whether that works in kubuntu or not.

**Comment by richrd** [comment] 2018-07-19 13:09
Thx! I'm on 17.10, I'll try and upgrade when I have time.

**Comment by richrd** [comment] 2018-07-19 15:29
Yeah, makes sense not to try and fix it in core. After all they are just unicode characters, and the browser should handle it. I found this extension and it kind of works. However it doesn't detect all emojis and they end up being a bit misaligned. Maybe I'll just wait for official support. https://chrome.google.com/webstore/detail/chromoji-emoji-for-google/cahedbegdkagmcjfolhdlechbkeaieki/related

**Comment by McInkay** [comment] 2018-07-20 07:20
Try this one as well. https://chrome.google.com/webstore/detail/emoji-swap-by-emojione/laaoconppkgneoeccdehhabfiojpekoa
