### ISSUE TITLE
Channel history hidden on channels with a lot of status messages

### ISSUE THREAD

**Issue by rossengeorgiev** [thelounge/thelounge#2900] opened 2018-11-20 15:37 UTC
* *Browser version:* Firefox 63
* *Device, operating system:* Windows 10
* *The Lounge version:* 3.0.0-rc.3
---

![image](https://user-images.githubusercontent.com/2720787/48776778-a4f60100-ecc8-11e8-9725-58ab93c33dc7.png)

Depending the amount of status messages, chat history can be hidden. In extreme cases with a whole lot more status messages I may need to click on "show older messages" multiple times. Then if I switch between channels, the history gets reset.

**Comment by xPaw** [comment] 2018-11-20 15:50
Duplicate of #422

**Closed by xPaw** 2018-11-20 15:50 UTC
