### ISSUE TITLE
Don't aggregate hidden messages when loading more messages

### ISSUE THREAD

**Issue by williamboman** [thelounge/thelounge#422] opened 2016-06-20 13:41 UTC
In channels where the actual text message vs. "ubiquitous messages that are hidden through settings" (e.g. join, part, quit) ratio is very low one can click the `Show more` button multiple times without it actually showing any new messages.

**Comment by astorije** [comment] 2016-09-15 05:25
See #608 for more details and reproduction steps.

**Comment by richrd** [comment] 2019-12-20 09:38
Should be fixed in v4 right @xPaw ?

**Comment by xPaw** [comment] 2019-12-20 09:39
It certainly has been improved by #3603

**Closed by xPaw** 2019-12-20 09:39 UTC
Labels: Type: Feature

**Comment by fuzzy76** [comment] 2020-03-31 06:41
I'm seeing this in 4.1.0?

**Comment by fuzzy76** [comment] 2020-03-31 06:45
Oh, I hit the 1000 max marker. By far, actually.

The reason is that I run [Bitlbee](https://www.bitlbee.org/) with the Facebook plugin, and it generates join/parts for every time a person among my Facebook friends go online or offline...
