### ISSUE TITLE
Support fallback encoding for lines that are not valid UTF-8

### ISSUE THREAD

**Issue by lorkki** [thelounge/thelounge#2299] opened 2018-03-26 10:31 UTC
There are lots of channels in the non-English parts of IRCnet where, for historical reasons, people still use clients that send ie. ISO 8859-* encodings or their Windows equivalents. Irssi, for instance, has built-in handling for this by allowing the user to set a fallback encoding that's used whenever UTF-8 decoding fails (this fallback is enabled by default and set to ISO 8859-1.).

After switching to The Lounge, this is the most obvious missing feature for me, since the non-Unicode characters show up as broken glyphs (�).

* *Node version:* official Docker image
* *Browser version:* any
* *Device, operating system:* any
* *The Lounge version:* v2.7.1

**Comment by xPaw** [comment] 2018-03-26 10:43
Duplicate of #1094

**Closed by xPaw** 2018-03-26 10:43 UTC
