### ISSUE TITLE
Support HTTP_PROXY and HTTPS_PROXY like matrix homeserver for air gapped connectivity (prefetching and previewing)

### ISSUE THREAD

**Issue by github-sys-admin** [thelounge/thelounge#4575] opened 2022-05-26 19:40 UTC
homeserver for matrix uses this for (everything) but it's namely useful if you want to do forward caching for a server that may frequently be used to retrieve content from the internet or for servers which have no means to access the internet except through the proxy; the server's requests are forwarded over tor through a haproxy egress controller: 

haproxy
```
frontend egress_tcp_proxy_frontend
  mode tcp
  bind 100.64.78.11:443
  bind 100.64.78.11:80
  bind 100.64.78.27:443
  bind 100.64.78.27:80
  default_backend tcp_backend

backend tcp_backend
  mode tcp
  server tor 100.64.65.18:9080
```
tor
```
HTTPTunnelPort                      100.64.65.18:9080
```
hoemserver docker compose 

```
   environment:
      - HTTP_PROXY=http://100.64.78.11:80/
      - HTTPS_PROXY=http://100.64.78.11:443/
```

it works.  I'm honestly kinda surprised I've seen a number of people asking for this and I'm pretty sure this is the point that has been largely missed; air gapping the service and restricting what it can connect out to by providing it a direct edge to what it needs to connect to and a proxy with very specific directives for everything else.

**Comment by brunnre8** [comment] 2022-05-26 21:55
Duplicate of https://github.com/thelounge/thelounge/issues/4297

**Closed by brunnre8** 2022-05-26 21:55 UTC
Labels: Type: Feature

**Comment by brunnre8** [comment] 2022-05-26 21:59
Not sure if this is a feature request or a workaround of yours.

There's multiple ways of restricting the access TL has via the usual name spacing measures of the kernel (least on Linux). You can happily reroute traffic through whatever VPN as long as it's transparent to TL.

The feature request aspect is covered by the linked issue already so I'm closing this

**Comment by github-sys-admin** [comment] 2022-05-29 12:14
a "workaround of mine" lol
