### ISSUE TITLE
Detect wrong encoding

### ISSUE THREAD

**Issue by Nek-** [thelounge/thelounge#3746] opened 2020-02-07 20:53 UTC
### Feature Description

Some users may not write with Unicode encoding. We can detect it because it sometimes does not match any standard character but known characters in another encoding. (I'm pretty sure some libraries already do the work)

What do you think about implementing it inside thelounge?

 :+1: to agree :-1: to disagree, please vote as team leader :) .

**Comment by xPaw** [comment] 2020-02-07 21:06
Duplicate of #2299
Duplicate of #1094
Duplicate of #371
Duplicate of #175

TL:DR: Detecting encoding is not trivial as you might seem to think, and my current stance is that TL will remain UTF-8 only.

Also see https://github.com/kiwiirc/irc-framework/pull/142

**Closed by xPaw** 2020-02-07 21:06 UTC
Labels: Type: Feature

**Comment by Nek-** [comment] 2020-02-07 22:13
@xPaw 2seconds research on google https://github.com/aadsm/jschardet

**Comment by xPaw** [comment] 2020-02-07 22:16
Read through the linked issues.

**Comment by Nek-** [comment] 2020-02-07 22:44
Does this mean "not interested for a patch, do not try you will lose your time besides it has been reported 5 times" ?

**Comment by ronilaukkarinen** [comment] 2020-03-16 16:38
Chiming in, noticed the same thing with äö characters that are very common here in Finland. Of course affects only some users, but can be very frustrating.

**Comment by ronilaukkarinen** [comment] 2020-07-08 20:22
Still bugging me. I have a very active IRC channel that has 100+ users daily and sometimes one of the users have wrong charset... trying to instruct them to change, but would it be better to make thelounge perfect? Lacking knowledge myself but that's why I'm bumping this...

**Comment by xPaw** [comment] 2020-07-09 07:59
There is no perfect/correct/side-effect-free fix for this issue (trying to detect charsets or auto fix them never perfects perfectly for all cases). It is also not very cheap performance wise when you want to do it as correctly as possible. All clients support using UTF-8 by now, it's just time to move on.

You can run ZNC in front of The Lounge which supports encoding fixing.

**Comment by Nek-** [comment] 2020-07-09 08:41
I agree with @ronilaukkarinen , it should be an option. Not having encoding correction in 2020 sounds not great. Also running ZNC in front of The Lounge sounds like "the lounge is useless, just don't use it" because they basically do same thing.

But as far as I understood, this issue will not be fixed in thelounge anyway? It should be fix in kiwiirc, right ? ( https://github.com/kiwiirc/irc-framework/pull/142 ).

**Comment by xPaw** [comment] 2020-07-09 09:06
Let's agree to disagree.

> Not having encoding correction in 2020 sounds not great

It's 2020 and there are still clients (users) not using Unicode, now that's not great. Blindly supporting multiple encodings without considering the risks can introduce bugs (like incorrectly decoding codepoints into newlines which would produce incorrect commands ­- ZNC had a security vuln like this).

IRCv3 mandates utf8 encoding for message tags, websockets spec will also likely mandate that.

See https://github.com/ircv3/ircv3-ideas/issues/38 for more thoughts on that.

> Also running ZNC in front of The Lounge sounds like "the lounge is useless, just don't use it" because they basically do the same thing.

ZNC is a bouncer, not a client.

> But as far as I understood, this issue will not be fixed in thelounge anyway?

Yes. `irc-framework` handles the decoding, so if you want to fix it it would go there for a correct implementation. That being said, it was already attempted at least twice with separate implementations, neither worked well enough.

**Comment by ronilaukkarinen** [comment] 2020-07-09 11:50
Thanks for the insight. I'm actually running TL via irssiproxy which acts as a bouncer. Chars works perfectly inside irssi session but not when viewing exactly the same conversation in thelounge. Isn't this exactly how znc would work? Saying this and not being familiar with znc though...

**Comment by xPaw** [comment] 2020-07-09 12:14
ZNC actually converts the messages before sending it to attached clients, I don't know if irssiproxy does that (it probably can, look up its documentation).

**Comment by ronilaukkarinen** [comment] 2020-07-09 12:21
Ok. Irssiproxy has a very poor documentation, as seen later here: https://irssi.org/documentation/startup/#proxies-and-irc-bouncers - it's only a feature for irssi, perhaps a bit incomplete.

I have already set up for example `recode_out_default_charset` to UTF-8 in irssi settings, but it has no effect here https://irssi.org/documentation/settings/

I just noticed `recode_fallback` is set to `CP1252`, maybe changing that to UTF-8 will help.

🤔

**Comment by xPaw** [comment] 2020-07-09 12:34
You're better off asking in irssi channel.

**Comment by ich777** [comment] 2020-08-19 15:24
Has this already been solved?
Also got this problem with �

**Comment by ronilaukkarinen** [comment] 2020-08-19 15:33
Not solved, probably never will, seems that way. I have been instructing people to change their charset like this: For mIRC the option should be "encode" instead of default, for irssi all recode and encode setting should be set to UTF-8. If people refuse to change their settings, have to live with the problem :(

**Comment by ich777** [comment] 2020-08-19 17:43
Sorry if this is a silly question but what should I change?
I use TheLounge on a Debian 10 headless installation and get this error...
The charset works correctly on all other applications and is set to UTF-8_en_US.
