### ISSUE TITLE
Using browser client onblur event for auto away

### ISSUE THREAD

**Issue by wzol** [thelounge/thelounge#3172] opened 2019-04-13 07:41 UTC
The scenario is when the user is connected, has the browser tab open - but that tab wasn't active for like 5 minutes. The idea is onblur starts a 5 minute setTimeout and if there is any action like focus event, or typing then the timeout is cleared else it sets the user away.

**Comment by xPaw** [comment] 2019-04-13 07:48
Duplicate of #2332

**Closed by xPaw** 2019-04-13 07:48 UTC
