### ISSUE TITLE
TypeError: Cannot set property 'openChannel' of undefined on 2.7.1

### ISSUE THREAD

**Issue by utopicdev** [thelounge/thelounge#2831] opened 2018-10-06 18:58 UTC
Using a stable version (2.7.1 @ Node.js 8.12.0 on linux x64), I get TheLounge constantly crashing when there are >100 simultaneous client connections.

> /usr/lib/node_modules/thelounge/src/client.js:466
>         this.attachedClients[socketId].openChannel = target.chan.id;
>                                                    ^
> 
> TypeError: Cannot set property 'openChannel' of undefined
>     at Client.open (/usr/lib/node_modules/thelounge/src/client.js:466:45)
>     at Socket.<anonymous> (/usr/lib/node_modules/thelounge/src/server.js:353:11)
>     at emitOne (events.js:116:13)
>     at Socket.emit (events.js:211:7)
>     at /usr/lib/node_modules/thelounge/node_modules/socket.io/lib/socket.js:513:12
>     at _combinedTickCallback (internal/process/next_tick.js:132:7)
>     at process._tickCallback (internal/process/next_tick.js:181:9)
>

**Comment by xPaw** [comment] 2018-10-06 19:00
This is a duplicate of #1995, and I think it's fixed on 3.0, try using the pre-release.

**Closed by xPaw** 2018-10-06 19:00 UTC
