### ISSUE TITLE
IRC Passwords Stored in Clear Text

### ISSUE THREAD

**Issue by superteece** [thelounge/thelounge#2614] opened 2018-07-03 19:59 UTC
* *Node version: 8.11.3* 
* *Browser version: n/a* 
* *Device, operating system: Server: Debian* 
* *The Lounge version: 2.7.1* 

---

Using the connect form in the web client saves the user's IRC password on The Lounge server in clear text in that user's profile. I'm not dev savvy enough to suggest a COA but something akin to WeeChat's /secure function might be the path to investigate.

**Comment by xPaw** [comment] 2018-07-03 20:02
Duplicate of #646

**Closed by xPaw** 2018-07-03 20:02 UTC

**Comment by superteece** [comment] 2018-07-03 22:29
Dang it I even looked for this....
